// flow-typed signature: a2d353977395e24aba3f323842ed8ddb
// flow-typed version: <<STUB>>/d3-geo_v^1.10.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-geo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-geo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-geo/dist/d3-geo' {
  declare module.exports: any;
}

declare module 'd3-geo/dist/d3-geo.min' {
  declare module.exports: any;
}

declare module 'd3-geo/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-geo/src/adder' {
  declare module.exports: any;
}

declare module 'd3-geo/src/area' {
  declare module.exports: any;
}

declare module 'd3-geo/src/bounds' {
  declare module.exports: any;
}

declare module 'd3-geo/src/cartesian' {
  declare module.exports: any;
}

declare module 'd3-geo/src/centroid' {
  declare module.exports: any;
}

declare module 'd3-geo/src/circle' {
  declare module.exports: any;
}

declare module 'd3-geo/src/clip/antimeridian' {
  declare module.exports: any;
}

declare module 'd3-geo/src/clip/buffer' {
  declare module.exports: any;
}

declare module 'd3-geo/src/clip/circle' {
  declare module.exports: any;
}

declare module 'd3-geo/src/clip/extent' {
  declare module.exports: any;
}

declare module 'd3-geo/src/clip/index' {
  declare module.exports: any;
}

declare module 'd3-geo/src/clip/line' {
  declare module.exports: any;
}

declare module 'd3-geo/src/clip/rectangle' {
  declare module.exports: any;
}

declare module 'd3-geo/src/clip/rejoin' {
  declare module.exports: any;
}

declare module 'd3-geo/src/compose' {
  declare module.exports: any;
}

declare module 'd3-geo/src/constant' {
  declare module.exports: any;
}

declare module 'd3-geo/src/contains' {
  declare module.exports: any;
}

declare module 'd3-geo/src/distance' {
  declare module.exports: any;
}

declare module 'd3-geo/src/graticule' {
  declare module.exports: any;
}

declare module 'd3-geo/src/identity' {
  declare module.exports: any;
}

declare module 'd3-geo/src/index' {
  declare module.exports: any;
}

declare module 'd3-geo/src/interpolate' {
  declare module.exports: any;
}

declare module 'd3-geo/src/length' {
  declare module.exports: any;
}

declare module 'd3-geo/src/math' {
  declare module.exports: any;
}

declare module 'd3-geo/src/noop' {
  declare module.exports: any;
}

declare module 'd3-geo/src/path/area' {
  declare module.exports: any;
}

declare module 'd3-geo/src/path/bounds' {
  declare module.exports: any;
}

declare module 'd3-geo/src/path/centroid' {
  declare module.exports: any;
}

declare module 'd3-geo/src/path/context' {
  declare module.exports: any;
}

declare module 'd3-geo/src/path/index' {
  declare module.exports: any;
}

declare module 'd3-geo/src/path/measure' {
  declare module.exports: any;
}

declare module 'd3-geo/src/path/string' {
  declare module.exports: any;
}

declare module 'd3-geo/src/pointEqual' {
  declare module.exports: any;
}

declare module 'd3-geo/src/polygonContains' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/albers' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/albersUsa' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/azimuthal' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/azimuthalEqualArea' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/azimuthalEquidistant' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/conic' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/conicConformal' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/conicEqualArea' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/conicEquidistant' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/cylindricalEqualArea' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/equalEarth' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/equirectangular' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/fit' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/gnomonic' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/identity' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/index' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/mercator' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/naturalEarth1' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/orthographic' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/resample' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/stereographic' {
  declare module.exports: any;
}

declare module 'd3-geo/src/projection/transverseMercator' {
  declare module.exports: any;
}

declare module 'd3-geo/src/rotation' {
  declare module.exports: any;
}

declare module 'd3-geo/src/stream' {
  declare module.exports: any;
}

declare module 'd3-geo/src/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-geo/dist/d3-geo.js' {
  declare module.exports: $Exports<'d3-geo/dist/d3-geo'>;
}
declare module 'd3-geo/dist/d3-geo.min.js' {
  declare module.exports: $Exports<'d3-geo/dist/d3-geo.min'>;
}
declare module 'd3-geo/rollup.config.js' {
  declare module.exports: $Exports<'d3-geo/rollup.config'>;
}
declare module 'd3-geo/src/adder.js' {
  declare module.exports: $Exports<'d3-geo/src/adder'>;
}
declare module 'd3-geo/src/area.js' {
  declare module.exports: $Exports<'d3-geo/src/area'>;
}
declare module 'd3-geo/src/bounds.js' {
  declare module.exports: $Exports<'d3-geo/src/bounds'>;
}
declare module 'd3-geo/src/cartesian.js' {
  declare module.exports: $Exports<'d3-geo/src/cartesian'>;
}
declare module 'd3-geo/src/centroid.js' {
  declare module.exports: $Exports<'d3-geo/src/centroid'>;
}
declare module 'd3-geo/src/circle.js' {
  declare module.exports: $Exports<'d3-geo/src/circle'>;
}
declare module 'd3-geo/src/clip/antimeridian.js' {
  declare module.exports: $Exports<'d3-geo/src/clip/antimeridian'>;
}
declare module 'd3-geo/src/clip/buffer.js' {
  declare module.exports: $Exports<'d3-geo/src/clip/buffer'>;
}
declare module 'd3-geo/src/clip/circle.js' {
  declare module.exports: $Exports<'d3-geo/src/clip/circle'>;
}
declare module 'd3-geo/src/clip/extent.js' {
  declare module.exports: $Exports<'d3-geo/src/clip/extent'>;
}
declare module 'd3-geo/src/clip/index.js' {
  declare module.exports: $Exports<'d3-geo/src/clip/index'>;
}
declare module 'd3-geo/src/clip/line.js' {
  declare module.exports: $Exports<'d3-geo/src/clip/line'>;
}
declare module 'd3-geo/src/clip/rectangle.js' {
  declare module.exports: $Exports<'d3-geo/src/clip/rectangle'>;
}
declare module 'd3-geo/src/clip/rejoin.js' {
  declare module.exports: $Exports<'d3-geo/src/clip/rejoin'>;
}
declare module 'd3-geo/src/compose.js' {
  declare module.exports: $Exports<'d3-geo/src/compose'>;
}
declare module 'd3-geo/src/constant.js' {
  declare module.exports: $Exports<'d3-geo/src/constant'>;
}
declare module 'd3-geo/src/contains.js' {
  declare module.exports: $Exports<'d3-geo/src/contains'>;
}
declare module 'd3-geo/src/distance.js' {
  declare module.exports: $Exports<'d3-geo/src/distance'>;
}
declare module 'd3-geo/src/graticule.js' {
  declare module.exports: $Exports<'d3-geo/src/graticule'>;
}
declare module 'd3-geo/src/identity.js' {
  declare module.exports: $Exports<'d3-geo/src/identity'>;
}
declare module 'd3-geo/src/index.js' {
  declare module.exports: $Exports<'d3-geo/src/index'>;
}
declare module 'd3-geo/src/interpolate.js' {
  declare module.exports: $Exports<'d3-geo/src/interpolate'>;
}
declare module 'd3-geo/src/length.js' {
  declare module.exports: $Exports<'d3-geo/src/length'>;
}
declare module 'd3-geo/src/math.js' {
  declare module.exports: $Exports<'d3-geo/src/math'>;
}
declare module 'd3-geo/src/noop.js' {
  declare module.exports: $Exports<'d3-geo/src/noop'>;
}
declare module 'd3-geo/src/path/area.js' {
  declare module.exports: $Exports<'d3-geo/src/path/area'>;
}
declare module 'd3-geo/src/path/bounds.js' {
  declare module.exports: $Exports<'d3-geo/src/path/bounds'>;
}
declare module 'd3-geo/src/path/centroid.js' {
  declare module.exports: $Exports<'d3-geo/src/path/centroid'>;
}
declare module 'd3-geo/src/path/context.js' {
  declare module.exports: $Exports<'d3-geo/src/path/context'>;
}
declare module 'd3-geo/src/path/index.js' {
  declare module.exports: $Exports<'d3-geo/src/path/index'>;
}
declare module 'd3-geo/src/path/measure.js' {
  declare module.exports: $Exports<'d3-geo/src/path/measure'>;
}
declare module 'd3-geo/src/path/string.js' {
  declare module.exports: $Exports<'d3-geo/src/path/string'>;
}
declare module 'd3-geo/src/pointEqual.js' {
  declare module.exports: $Exports<'d3-geo/src/pointEqual'>;
}
declare module 'd3-geo/src/polygonContains.js' {
  declare module.exports: $Exports<'d3-geo/src/polygonContains'>;
}
declare module 'd3-geo/src/projection/albers.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/albers'>;
}
declare module 'd3-geo/src/projection/albersUsa.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/albersUsa'>;
}
declare module 'd3-geo/src/projection/azimuthal.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/azimuthal'>;
}
declare module 'd3-geo/src/projection/azimuthalEqualArea.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/azimuthalEqualArea'>;
}
declare module 'd3-geo/src/projection/azimuthalEquidistant.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/azimuthalEquidistant'>;
}
declare module 'd3-geo/src/projection/conic.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/conic'>;
}
declare module 'd3-geo/src/projection/conicConformal.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/conicConformal'>;
}
declare module 'd3-geo/src/projection/conicEqualArea.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/conicEqualArea'>;
}
declare module 'd3-geo/src/projection/conicEquidistant.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/conicEquidistant'>;
}
declare module 'd3-geo/src/projection/cylindricalEqualArea.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/cylindricalEqualArea'>;
}
declare module 'd3-geo/src/projection/equalEarth.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/equalEarth'>;
}
declare module 'd3-geo/src/projection/equirectangular.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/equirectangular'>;
}
declare module 'd3-geo/src/projection/fit.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/fit'>;
}
declare module 'd3-geo/src/projection/gnomonic.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/gnomonic'>;
}
declare module 'd3-geo/src/projection/identity.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/identity'>;
}
declare module 'd3-geo/src/projection/index.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/index'>;
}
declare module 'd3-geo/src/projection/mercator.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/mercator'>;
}
declare module 'd3-geo/src/projection/naturalEarth1.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/naturalEarth1'>;
}
declare module 'd3-geo/src/projection/orthographic.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/orthographic'>;
}
declare module 'd3-geo/src/projection/resample.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/resample'>;
}
declare module 'd3-geo/src/projection/stereographic.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/stereographic'>;
}
declare module 'd3-geo/src/projection/transverseMercator.js' {
  declare module.exports: $Exports<'d3-geo/src/projection/transverseMercator'>;
}
declare module 'd3-geo/src/rotation.js' {
  declare module.exports: $Exports<'d3-geo/src/rotation'>;
}
declare module 'd3-geo/src/stream.js' {
  declare module.exports: $Exports<'d3-geo/src/stream'>;
}
declare module 'd3-geo/src/transform.js' {
  declare module.exports: $Exports<'d3-geo/src/transform'>;
}
