// flow-typed signature: b321b5a18a97f9fcc66ee19f209fad26
// flow-typed version: <<STUB>>/d3-tile_v0.0.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-tile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-tile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-tile/build/d3-tile' {
  declare module.exports: any;
}

declare module 'd3-tile/build/d3-tile.min' {
  declare module.exports: any;
}

declare module 'd3-tile/src/tile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-tile/build/d3-tile.js' {
  declare module.exports: $Exports<'d3-tile/build/d3-tile'>;
}
declare module 'd3-tile/build/d3-tile.min.js' {
  declare module.exports: $Exports<'d3-tile/build/d3-tile.min'>;
}
declare module 'd3-tile/index' {
  declare module.exports: $Exports<'d3-tile'>;
}
declare module 'd3-tile/index.js' {
  declare module.exports: $Exports<'d3-tile'>;
}
declare module 'd3-tile/src/tile.js' {
  declare module.exports: $Exports<'d3-tile/src/tile'>;
}
