// flow-typed signature: 97204741d0c65bb566dda00a6fe93532
// flow-typed version: <<STUB>>/d3-zoom_v^1.7.3/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-zoom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-zoom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-zoom/dist/d3-zoom' {
  declare module.exports: any;
}

declare module 'd3-zoom/dist/d3-zoom.min' {
  declare module.exports: any;
}

declare module 'd3-zoom/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-zoom/src/constant' {
  declare module.exports: any;
}

declare module 'd3-zoom/src/event' {
  declare module.exports: any;
}

declare module 'd3-zoom/src/index' {
  declare module.exports: any;
}

declare module 'd3-zoom/src/noevent' {
  declare module.exports: any;
}

declare module 'd3-zoom/src/transform' {
  declare module.exports: any;
}

declare module 'd3-zoom/src/zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-zoom/dist/d3-zoom.js' {
  declare module.exports: $Exports<'d3-zoom/dist/d3-zoom'>;
}
declare module 'd3-zoom/dist/d3-zoom.min.js' {
  declare module.exports: $Exports<'d3-zoom/dist/d3-zoom.min'>;
}
declare module 'd3-zoom/rollup.config.js' {
  declare module.exports: $Exports<'d3-zoom/rollup.config'>;
}
declare module 'd3-zoom/src/constant.js' {
  declare module.exports: $Exports<'d3-zoom/src/constant'>;
}
declare module 'd3-zoom/src/event.js' {
  declare module.exports: $Exports<'d3-zoom/src/event'>;
}
declare module 'd3-zoom/src/index.js' {
  declare module.exports: $Exports<'d3-zoom/src/index'>;
}
declare module 'd3-zoom/src/noevent.js' {
  declare module.exports: $Exports<'d3-zoom/src/noevent'>;
}
declare module 'd3-zoom/src/transform.js' {
  declare module.exports: $Exports<'d3-zoom/src/transform'>;
}
declare module 'd3-zoom/src/zoom.js' {
  declare module.exports: $Exports<'d3-zoom/src/zoom'>;
}
