// flow-typed signature: 573f4f359758e30b342678f29ee02a7f
// flow-typed version: <<STUB>>/webpack-blocks_v^1.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-blocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-blocks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-blocks/index' {
  declare module.exports: $Exports<'webpack-blocks'>;
}
declare module 'webpack-blocks/index.js' {
  declare module.exports: $Exports<'webpack-blocks'>;
}
